auth sets in
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Soundwave pull request #42
Opened 2024-07-04 11:33 UTC by emmanuelle-c

2024-07-04 11:38 UTC, YannLahellec approved these changes

2024-07-04 12:06 UTC, Alexandre78R requested changes

2024-07-04 12:06 UTC, Alexandre78R commented on server/app/services/auth.js
> +    }
add else response error 403 not perission

2024-07-04 12:06 UTC, Alexandre78R commented on server/app/services/auth.js
> +    }
add else response error 401 not perission

2024-07-04 12:06 UTC, Alexandre78R commented on server/app/services/auth.js
> +    }
add else response error 403 not perission

2024-07-05 07:40 UTC, Alexandre78R approved these changes
Good !

2024-07-05 07:40 UTC, merged